### ISSUE TITLE
ImportError: cannot import name 'ugettext_lazy' from 'django.utils.translation'

### ISSUE THREAD

**Issue by scheung38** [django-hurricane/django-hurricane#105]
What is the difference between this repo vs hurricane-based-helm-template?

Which one should we use if needing to deploy Django as well as a database?

Do we clone this repo,  hurricane-based-helm-template or both given the context?

But just cloned repo today, so seeing the following:

(.venv) python src/manage.py serve --autoreload --static

ImportError: cannot import name 'ugettext_lazy' from 'django.utils.translation' ($HOME/Documents/paf/.venv/lib/python3.11/site-packages/django/utils/translation/__init__.py)

(.venv) python --version                                
Python 3.11.1

Tried:
(.venv) pip install --upgrade Django 

(.venv) pip list                                        
Package         Version
asgiref        3.6.0
Django         4.1.5
pip            22.3.1
setuptools     65.6.3
split-settings 1.0.0
sqlparse       0.4.3
wheel          0.38.4

(.venv) az login is ok

(.venv) kubens
aks-command
myprod
mystaging
default
gatekeeper-system
kube-node-lease
kube-public
kube-system
loft
loft-tasks

(.venv) kubectl get nodes
NAME                             STATUS   ROLES   AGE     VERSION
aks-system-XXXXXXX-vmss000000   Ready    agent   5d20h   v1.23.12
aks-system-XXXXXXX-vmss000001   Ready    agent   5d20h   v1.23.12
aks-system-XXXXXXX-vmss000002   Ready    agent   5d20h   v1.23.12
aks-user-XXXXXXX-vmss000000     Ready    agent   5d20h   v1.23.12
aks-user-XXXXXXX-vmss000001     Ready    agent   5d20h   v1.23.12
aks-user-XXXXXXX-vmss000002     Ready    agent   5d20h   v1.23.12

The Dockerfile is using python3.9-slim so is that the issue?

What is going on please? As you can see AKS cluster is readily available since last AKS deploy. Or have I missed installation step?

**Comment by SteinRobert** [comment]
Seems like a bug in your application. This import is not used in django-hurricane as far as I am aware. You tried any of our guides?

**Comment by SteinRobert** [comment]
So it's a problem with the cookiecutter template not django hurricane - I guess at least.
Try to downgrade Django to 3.x Probably there is some incompatible import within the cookiecutter template.

**Comment by scheung38** [comment]
Thanks @SteinRobert 

What is the difference between this repo vs hurricane-based-helm-template? For my use case I have database with via PostgreSQL or MongoDB via Djongo

**Comment by SteinRobert** [comment]
This repo is a django app you can use to extend Django for better Kubernetes integration.
hurricane-based-helm-template is a cookiecutter template to generate helm charts for your django-hurricane based application.
