### ISSUE TITLE
Expose Prometheus Metrics

### ISSUE THREAD

**Issue by tobifroe** [django-hurricane/django-hurricane#108]
I'd like to implement prometheus-compatible instrumentation/metrics for Django Hurricane.

To start things off, I have the following basic HTTP metrics in mind:
- Request Latency (Histogram, labeled with http method name and request path)
- Total Request Count (Counter)

To do so, I'd install the [prometheus python client](https://github.com/prometheus/client_python) package, add classes matching the metrics I mentioned above to the existing metrics module and add another optional (enabled via CLI flag, I guess?) handler that provides the prometheus endpoint. 

The actual metric collection would happen in the `HurricaneApplication.log_request` method (where request latency is already calculated), much like the metrics that are already collected.

Please feel free to drop your thoughts :)

Edit: 
I can't assign labels in this repo, feel free to label this as you see fit.

**Comment by Schille** [comment]
Wow! That was easy to implement thanks to @SteinRobert metrics components. Let's check my implementation. If it's fine, we can release that with the next version of hurricane.
