### ISSUE TITLE
Add Django 4.2 support

### ISSUE THREAD

**Issue by tschale** [django-hurricane/django-hurricane#110]
Currently Hurricane can't even be installed. We need to fix that and need to make it work with Django 4.2

ToDos:
- [x] bump install requirement asgiref to 3.6.0, see https://docs.djangoproject.com/en/4.2/releases/4.2/#miscellaneous

**Comment by hng** [comment]
+1

**Comment by Schille** [comment]
This is resolved with version 1.4.0
