### ISSUE TITLE
Leaking DB Connections

### ISSUE THREAD

**Issue by SteinRobert** [django-hurricane/django-hurricane#124]
In version 1.4.0 we have been experiencing issues, that the amount of open database connections is increasing over time. It seems there is some leak, causing the open (idle) database connections to grow which leads to the problem, that the database at some point refuses to open new connections.

**Comment by Schille** [comment]
It's very likely not a bug of Hurricane.

**Comment by Schille** [comment]
Try Version 1.5.0
Maybe limiting the `--workers` helps you out.
