### ISSUE TITLE
Is `--autoreload` parameter recommended for production usage?

### ISSUE THREAD

**Issue by viginti23** [django-hurricane/django-hurricane#132]
Hi there, 
We have a project running with django-hurricane setup, however we are wondering if the `--autoreload` parameter is something that could somehow interfere with the proper work in the production setup?
We are experiencing some issues with grpc clients and investigating any potential bottlenecks and hotspots.

**Comment by tschale** [comment]
Hi @viginti23, the `--autoreload` flag might influence a production setup. It is mainly intended for development environments, where it is convenient to have the app server reload when there are code changes. This is not a use case we see in a production setup.

Do you have this case, is autoreloading a requirement you have for a production setup? If not, we would recommend to remove the flag in production.

**Comment by viginti23** [comment]
Thank you for the info, we removed the flag and saved a ton of CPU. :)
