### ISSUE TITLE
Add django 3.2 support (with native async requests)

### ISSUE THREAD

**Issue by Schille** [django-hurricane/django-hurricane#18]

**Comment by Schille** [comment]
At the moment it seems that django ~ 3 is not supported at all. @vvvityaaa could you have a look and add test cases with different django versions too?

**Comment by Schille** [comment]
The current release from tag 0.8.8 resolves issues with postgresql and django 3.2 in the meantime.

**Comment by vvvityaaa** [comment]
Is this problem resolved with the current release?

**Comment by tschale** [comment]
@Schille Do we have something to do here? We're using hurricane on some projects with 3.2

**Comment by Schille** [comment]
async is not yet supported, but version 1.4.0 adds Django >4.2 compatibility.
