### ISSUE TITLE
Allow probe port to be bound to all interfaces (and not just localhost) during development

### ISSUE THREAD

**Issue by Schille** [django-hurricane/django-hurricane#57]
The current implementation is perfectly working in production scenarios.
However, during development (especially in container-based development) it would be helpful make it possible to bind the probe application to all interfaces, too. That would make it more convenient to develop probe-based check code.

That bothered me when using Hurricane with Gefyra while forwarding the probe ports. They are not answered to Kubernetes since the probe request does not originate from localhost (as it would be running in the cluster) but is proxied.

**Comment by vvvityaaa** [comment]
In #69 it was discussed, that all interfaces is a default for tornado applications.
