### ISSUE TITLE
README improvements

### ISSUE THREAD

**Issue by SteinRobert** [django-hurricane/django-hurricane#74]
I was looking for the installation instructions, as well as the "happy path" to make use of Django Hurricane. The installation is located at the end of the README, the usage isn't included at all. This should probably be pretty much at the top of the README file.

**Comment by tschale** [comment]
I think we actually removed further documentation from the readme after discussion with @Schille not to long ago. To have the readthedocs as the main source and as we already struggled to keep for example both argument listings synchronously up to date...
I would be totally open to include a minimal usage example. What do you think @Schille @vvvityaaa @SteinRobert?

**Comment by vvvityaaa** [comment]
I think, adding a minimal usage example would make sense. Also, I think,  it does not make sense to have such a long to-do list in the README. We can either have it only in the documentation or in a sort of consolidated issue, that includes all the future tasks
