### ISSUE TITLE
Mute K8s probe logs (liveness, readiness probes) for default configuration

### ISSUE THREAD

**Issue by Schille** [django-hurricane/django-hurricane#80]

**Comment by buschNT** [comment]
I often encounter the following logs during debugging, which makes it quite difficult to find interesting logs:

![Screenshot from 2022-04-22 16-00-41](https://user-images.githubusercontent.com/6874607/164743443-2feb619b-60fc-4b0a-aef0-18073543d74d.png)

I think it would be better if these log outputs would not be logged by default. Unfortunately it seens like it is currently not possible to control the logs of the probes separately from other logs.
Maybe the alive and readyness probes logs can be handled by a separate logger, thus allowing better customization?

I guess a good starting points in the code would be `from hurricane.server.loggers import access_log` and the `HurricaneApplication`.

**Comment by georgkrause** [comment]
As discussed with @Schille the plan is to extend our `HurricaneApplication` which will check for a Django Setting in `log_request` before actually logging anything. I already have an implementation, but I need to do some proper testing next week and add documentation.
